ParagonIntegrationsWeb/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^EMon/', include('emon.urls')),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

#Add URL maps to redirect the base URL to emon, this is only temporary until the rest of the website is up and running
urlpatterns += [
    url(r'^$', RedirectView.as_view(url='/EMon/', permanent=True)),
]

# Serve static files during development
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

emon/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^installations/$', views.InstallationListView.as_view(), name='installations'),
    url(r'^installation/(?P<pk>\d+)/$', views.InstallationDetailView.as_view(), name='installation-detail'),
    url(r'^meters/$', views.MeterListView.as_view(), name='meters'),
    url(r'^meter/(?P<pk>\d+)/$', views.MeterDetailView.as_view(), name='meter-detail'),
    url(r'^channels/$', views.ChannelListView.as_view(), name='channels'),
    url(r'^channel/(?P<pk>\d+)/$', views.ChannelDetailView.as_view(), name='channel-detail'),
]

emon/models.py
from django.db import models
from django.urls import reverse  # Used to generate urls by reversing the URL patterns
import uuid


class Installations(models.Model):
    """
    Model representing a book genre (e.g. Science Fiction, Non Fiction).
    """
    id = models.AutoField(primary_key=True)
    address = models.CharField(max_length=200, help_text="Enter the address of this installation")
    name = models.CharField(max_length=200, help_text="Enter a descriptive name for this installation")

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.name

    def get_absolute_url(self):
        """
        Returns the url to access a particular installation.
        """
        return reverse('installation-detail', args=[str(self.id)])

class Meters(models.Model):
    """
    Model representing a book genre (e.g. Science Fiction, Non Fiction).
    """
    id = models.IntegerField(primary_key=True, help_text="ID of the meter")
    serial = models.CharField(max_length= 200,unique=True)
    num_channels = models.PositiveSmallIntegerField()
    installation_date = models.DateField()
    installation = models.ForeignKey('Installations', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return str(self.id)

    def get_absolute_url(self):
        """
        Returns the url to access a particular meter.
        """
        return reverse('meter-detail', args=[str(self.id)])

class Channels(models.Model):
    """
    Model representing a book genre (e.g. Science Fiction, Non Fiction).
    """
    id = models.IntegerField(primary_key=True, help_text="Channel ID(consists of meter ID and channel number")
    meter = models.ForeignKey('Meters', on_delete=models.SET_NULL, null=True)
    description = models.CharField(max_length=200)

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return str(self.id)

    def get_absolute_url(self):
        """
        Returns the url to access a particular channel.
        """
        return reverse('channel-detail', args=[str(self.id)])

class ChannelData(models.Model):
    """
    Model representing a book genre (e.g. Science Fiction, Non Fiction).
    """
    channel = models.ForeignKey('Channels', on_delete=models.SET_NULL, null=True)
    timestamp = models.DateTimeField()
    vrms = models.DecimalField(max_digits=5, decimal_places=2)
    irms = models.DecimalField(max_digits=5, decimal_places=2)
    units_left = models.DecimalField(max_digits=10, decimal_places=6)
    unitsused = models.DecimalField(max_digits=8, decimal_places=6)
    unit_counter = models.DecimalField(max_digits=13, decimal_places=6)

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.timestamp

emon/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Installations, Meters, Channels, ChannelData

# Create your views here.

class Index(TemplateView):
    template_name = "index.html"


class InstallationListView(generic.ListView):
    model = Installations
    queryset = Installations.objects.order_by('id')


class InstallationDetailView(generic.DetailView):
    model = Installations


class MeterListView(generic.ListView):
    model = Meters
    queryset = Meters.objects.order_by('id')


class MeterDetailView(generic.DetailView):
    model = Meters

class ChannelListView(generic.ListView):
    model = Channels
    queryset = Channels.objects.order_by('id')


class ChannelDetailView(generic.DetailView):
    model = Channels

emon/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% block title %}<title>Paragon Integrations</title>{% endblock title %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!--script type="text/javascript">
        $(document).ready(function() {
            // get current URL path and assign 'active' class
            var pathname = window.location.pathname;
            $('.nav > li > a[href="'+pathname+'"]').parent().addClass('active');
        })
    </script-->


    <!-- Add additional CSS in static file -->
    {% load static %}
    <script type="text/javascript" src="{% static 'js/myscripts.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

</head>

<body>

    <div class="above-nav">
        <div class="container">
            <div class="col-sm-9">
                {% block header %}
                    <h1>My Default Header</h1>
                {% endblock header %}
            </div>
            <div class="col-sm-3 hidden-xs text-right">
                {% block loginarea %}
                    <div>
                        {% if user.is_authenticated %}
                            <span class="glyphicon glyphicon-user"></span> Welcome, {{ user.get_username }}
                        {% endif %}
                    </div>
                {% endblock loginarea %}
            </div>
        </div>
    </div>

    <div class="nav-wrapper" style="height:51px;">
        <nav class="nav navbar-inverse" data-spy="affix" data-offset-top="100">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main_navbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">WebSiteName</a>
                </div>
                <div class="collapse navbar-collapse" id="main_navbar">
                    <ul class="nav navbar-nav">
                        {% block navigation_bar %}
                        <li class="active"><a href="#">Home</a></li>
                        {% endblock navigation_bar %}
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            <li class="navbar-text">Welcome,</li>
                            <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ user.get_username }} <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="/user/preferences"><span class="glyphicon glyphicon-cog"></span> Preferences</a></li>
                                    <li><a href="/help/support"><span class="glyphicon glyphicon-envelope"></span> Contact Support</a></li>
                                    <li class="divider"></li>
                                    <li><a href="{% url 'logout' %}?next={{request.path}}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
                                </ul>
                            </li>
                        {% else %}
                            <button type="button" class="btn navbar-btn" data-toggle="modal" data-target="#LoginModal"><span class="glyphicon glyphicon-log-in"></span> Login</button>
                        {% endif %}

                    </ul>
                </div>
            </div>
        </nav>
    </div>

    <!-- Modal -->
    <div id="LoginModal" class="modal fade" role="dialog">
      <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h1 class="modal-title">Login to Your account</h1>
          </div>
          <div class="modal-body">
            <form action="{% url 'login' %}" method="post">
                {% csrf_token %}
                <input type="text" name="username" placeholder="Username">
                <input type="password" name="password" placeholder="Password">
                <input type="submit" name="login" class="login loginmodal-submit" value="Login">
                <input type="hidden" name="next" value="{{ next }}" />
            </form>
            <div class="login-help">
                <a href="#">Forgot Password</a>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
        {% block content %}

            <p>Default body</p>

        {% endblock content %}
    </div>

    <div class="container">
        {% block footer %}


        {% endblock footer %}
    </div>

</body>
</html>

emon/templates/emon/channels_detail.html
{% extends "emon_generic.html" %}

{% block content %}
    <p><strong>Channel data goes here</strong></p>


{% endblock content %}

emon/templates/emon/channels_list.html
{% extends "emon_generic.html" %}

{% block content %}
    <h1>Channels</h1>

    {% if channels_list %}
    <ul>

      {% for channel in object_list %}
      <li>
        <a href="{{ channel.get_absolute_url }}">{{ channel.id }}</a> ({{channel.meter}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no Channels.</p>
    {% endif %}
{% endblock %}

emon/templates/emon/installations_detail.html
{% extends "emon_generic.html" %}

{% block content %}
    <p><strong>ID:</strong> <a href="">{{ installations.id }}</a></p>
    <p><strong>Address:</strong> <a href="">{{ installations.address }}</a></p>
    <p><strong>Name:</strong> <a href="">{{ installations.name }}</a></p>
    <br>
    <h4>Meters:</h4>
    <br>
    {% for meter in installations.meters_set.all %}
        <p><a href="{{ meter.get_absolute_url }}">{{ meter.id }}</a></p>
    {% endfor %}
{% endblock content %}

emon/templates/emon/installations_list.html
{% extends "emon_generic.html" %}

{% block content %}
    <h1>Installations</h1>

    {% if installations_list %}
    <ul>

      {% for installation in object_list %}
      <li>
        <a href="{{ installation.get_absolute_url }}">{{ installation.name }}</a> ({{installation.address}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no installations.</p>
    {% endif %}
{% endblock %}

emon/templates/emon/meters_detail.html
{% extends "emon_generic.html" %}

{% block content %}
    <p><strong>ID:</strong> <a href="">{{ meters.id }}</a></p>
    <p><strong>Serial:</strong> <a href="">{{ meters.serial }}</a></p>
    <p><strong>Installation:</strong> <a href="">{{ meters.installation }}</a></p>
    <br>
    <h4>Channels:</h4>
    <br>
    {% for channel in meters.channels_set.all %}
        <p><a href="{{ channel.get_absolute_url }}">{{ channel.id }}</a></p>
    {% endfor %}
{% endblock content %}

emon/templates/emon/meters_list.html
{% extends "emon_generic.html" %}

{% block content %}
    <h1>Meters</h1>

    {% if meters_list %}
    <ul>

      {% for meter in object_list %}
      <li>
        <a href="{{ meter.get_absolute_url }}">{{ meter.id }}</a> ({{meter.installation}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no meters.</p>
    {% endif %}
{% endblock %}

emon/templates/emon_generic.html
{% extends "base_generic.html" %}

{% block navigation_bar %}
    <li><a href="{% url 'index' %}">Home</a></li>
    <li><a href="{% url 'installations' %}">Installations</a></li>
    <li><a href="{% url 'meters' %}">Meters</a></li>
    <li><a href="{% url 'channels' %}">Channels</a></li>
{% endblock %}

emon/templates/index.html
{% extends "emon_generic.html" %}

{% block content %}

    <h1>Index Page</h1>
    <p>should contain an overview later</p>

    <p>
    Use this document as a way to quickly start any new project. All you get is this text and a mostly barebones HTML document. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Aenean lacinia bibendum nulla sed consectetur. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.

Aenean lacinia bibendum nulla sed consectetur. Cras mattis consectetur purus sit amet fermentum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec ullamcorper nulla non metus auctor fringilla.

Sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam id dolor id nibh ultricies vehicula ut id elit. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Donec sed odio dui. Nulla vitae elit libero, a pharetra augue. Sed posuere consectetur est at lobortis.

Use this document as a way to quickly start any new project. All you get is this text and a mostly barebones HTML document. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Aenean lacinia bibendum nulla sed consectetur. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.

Aenean lacinia bibendum nulla sed consectetur. Cras mattis consectetur purus sit amet fermentum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec ullamcorper nulla non metus auctor fringilla.

Sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam id dolor id nibh ultricies vehicula ut id elit. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Donec sed odio dui. Nulla vitae elit libero, a pharetra augue. Sed posuere consectetur est at lobortis.

Use this document as a way to quickly start any new project. All you get is this text and a mostly barebones HTML document. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Aenean lacinia bibendum nulla sed consectetur. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.

Aenean lacinia bibendum nulla sed consectetur. Cras mattis consectetur purus sit amet fermentum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec ullamcorper nulla non metus auctor fringilla.

Sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam id dolor id nibh ultricies vehicula ut id elit. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Donec sed odio dui. Nulla vitae elit libero, a pharetra augue. Sed posuere consectetur est at lobortis.

Use this document as a way to quickly start any new project. All you get is this text and a mostly barebones HTML document. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Aenean lacinia bibendum nulla sed consectetur. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.

Aenean lacinia bibendum nulla sed consectetur. Cras mattis consectetur purus sit amet fermentum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec ullamcorper nulla non metus auctor fringilla.

Sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam id dolor id nibh ultricies vehicula ut id elit. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Donec sed odio dui. Nulla vitae elit libero, a pharetra augue. Sed posuere consectetur est at lobortis.
    </p>

    <p>
    Use this document as a way to quickly start any new project. All you get is this text and a mostly barebones HTML document. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Aenean lacinia bibendum nulla sed consectetur. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.

Aenean lacinia bibendum nulla sed consectetur. Cras mattis consectetur purus sit amet fermentum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec ullamcorper nulla non metus auctor fringilla.

Sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam id dolor id nibh ultricies vehicula ut id elit. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Donec sed odio dui. Nulla vitae elit libero, a pharetra augue. Sed posuere consectetur est at lobortis.

Use this document as a way to quickly start any new project. All you get is this text and a mostly barebones HTML document. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Aenean lacinia bibendum nulla sed consectetur. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.

Aenean lacinia bibendum nulla sed consectetur. Cras mattis consectetur purus sit amet fermentum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec ullamcorper nulla non metus auctor fringilla.

Sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam id dolor id nibh ultricies vehicula ut id elit. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Donec sed odio dui. Nulla vitae elit libero, a pharetra augue. Sed posuere consectetur est at lobortis.

Use this document as a way to quickly start any new project. All you get is this text and a mostly barebones HTML document. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Aenean lacinia bibendum nulla sed consectetur. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.

Aenean lacinia bibendum nulla sed consectetur. Cras mattis consectetur purus sit amet fermentum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec ullamcorper nulla non metus auctor fringilla.

Sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam id dolor id nibh ultricies vehicula ut id elit. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Donec sed odio dui. Nulla vitae elit libero, a pharetra augue. Sed posuere consectetur est at lobortis.

Use this document as a way to quickly start any new project. All you get is this text and a mostly barebones HTML document. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Aenean lacinia bibendum nulla sed consectetur. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.

Aenean lacinia bibendum nulla sed consectetur. Cras mattis consectetur purus sit amet fermentum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec ullamcorper nulla non metus auctor fringilla.

Sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam id dolor id nibh ultricies vehicula ut id elit. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Donec sed odio dui. Nulla vitae elit libero, a pharetra augue. Sed posuere consectetur est at lobortis.
    </p>



{% endblock content %}